name: test deploy wait

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
    staging-test:
        environment: staging
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name : echo stuff
              run: |
                echo "stuff"

    prod-test:
        environment: prod
        runs-on: ubuntu-latest
        needs: staging-test
        permissions:
            contents: read

        steps:
            - name : echo stuff
              run: |
                echo "prod stuff" 